### ISSUE TITLE
Worflow > Upload Worflow > If user edit the workflow again, system discard the previous record. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#152]
As you can view in the attached video, the user has already uploaded the banner image, file, and main document. 
But when the user edits it, all the data gets removed. 

https://share.vidyard.com/watch/x6Uo7fg5Gexo5pfqtgSvRC?

**Comment by bioworkflows** [comment]
This looks like #153 since you entered lower price for extended license than regular license. The error caused the loss of all data, which should have been fixed now.

**Comment by Mashhood-Ehsan** [comment]
Still facing the same issue, when the user edits the workflow. The already entered data i.e. banner image, file, and main document get removed.

Please check the newly added video. 

https://share.vidyard.com/watch/CNHEieaigERgxPbXo5iCPq?

**Comment by BoPeng** [comment]
I reproduced this once but then I cannot. Wondering what it takes for this to happen more often.

**Comment by BoPeng** [comment]
@Mashhood-Ehsan It looks like a timing issue. More specifically, when the workflow is being processed, its attachments can be modified during which they are not "hooked" to the workflow. If we revise a workflow when it is being processed, the workflows can be unavailable. Saving the workflow with missing attachment information will remove the attachments.

I have disallowed the "Edit" button when the workflow is being processed, and editing workflows after processing is done appears to be ok.

**Comment by Mashhood-Ehsan** [comment]
Fine, understood.
I have tested it again and now it's working fine. so closing it.

![Screenshot (1460)](https://user-images.githubusercontent.com/60692597/199402190-8ffbd409-03ea-43f1-9cd5-1dcc693b65cb.png)


![Screenshot (1461)](https://user-images.githubusercontent.com/60692597/199402208-bc492cf5-6fbc-4cfa-a084-9d0fa3b95397.png)
