### ISSUE TITLE
Home > Dashboard > Upload Workflow > Whenever user add existing keyword, along with that 'new' keyword also keeps populating everytime.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#30]
https://www.loom.com/share/5450f9b011c449a18e45d832a61c2c3a

**Comment by BoPeng** [comment]
This should have been fixed. Please confirm.

**Comment by Mashhood-Ehsan** [comment]
![7](https://user-images.githubusercontent.com/60692597/140641700-a015a54b-48d1-44d0-b732-5cdde4ec0e01.PNG)

Still facing same issue
